const { writeFileSync } = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const frontend = path.resolve(__dirname, '..');
try {
  const apiUrl = new URL(process.env.API_URL || '');
  if (apiUrl.protocol !== 'https:' || apiUrl.username || apiUrl.password || apiUrl.search || apiUrl.hash) {
    throw new Error('API_URL must be an HTTPS URL without credentials, query parameters, or a fragment.');
  }
  const basePath = process.env.PAGES_BASE_PATH || '/';
  if (!basePath.startsWith('/') || basePath.startsWith('//') || /[?#\\\s]/.test(basePath)) {
    throw new Error('PAGES_BASE_PATH must be a URL path such as /music-player/ or /.');
  }
  const baseHref = basePath.replace(/\/+$/, '') + '/';
  const environment = {
    production: true,
    apiUrl: apiUrl.href.replace(/\/+$/, ''),
    useHashRouting: true
  };
  writeFileSync(
    path.join(frontend, 'src/environments/environment.pages.ts'),
    '// Generated by scripts/build-pages.cjs; do not commit.\nexport const environment = ' +
      JSON.stringify(environment, null, 2) + ';\n'
  );
  const result = spawnSync(process.execPath, [
    path.join(frontend, 'node_modules/@angular/cli/bin/ng.js'),
    'build', '--configuration=production,pages', '--base-href', baseHref
  ], { cwd: frontend, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status || 1);
  writeFileSync(path.join(frontend, 'dist/music-player-frontend/.nojekyll'), '');
} catch (error) {
  console.error('Pages build failed: ' + error.message +
    '\nSet API_URL to your deployed backend API, e.g. https://api.example.com/api.');
  process.exit(1);
}
